Pearl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('shop/', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="ShopHome"),
    path('about/', views.about, name="AboutUs"),
    path('contact/', views.contact, name="ContactUs"),
    path('tracker/', views.tracker, name="TrackingStatus"),
    path('product/<slug>/', views.productView, name="product"),
    path('product_images/', views.productImages),
    path('cart/', views.CartView, name='cart'),
    path('cart/<slug>/', views.updateCart, name='cartupdate'),
    path('checkout/', views.checkout, name="Checkout"),
    path('search/', views.search, name="Search"),
    path('signup/', views.signup, name="signup"),
    path('uname/', views.username_validation, name= "unamevalidation"),
    path('login/', views.login_validate, name="login"),
    path('loginpage/', views.login_page, name='loginpage'),
    path('logout/', views.logout_validate, name="logout"),
    path('ajax_email_signup/', views.ajax_email_signup, name="ajax_email_signup"),
    path('ajax_mobile_signup/', views.ajax_mobile_signup, name="ajax_mobile_signup"),

    path('temp', views.temp, name = 'temp'),
]

shop/models.py
from time import time
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.timezone import now
from django.core.files.storage import default_storage

class Pearl_Users(AbstractUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    date_of_birth = models.DateField(default=now)
    country = models.CharField(max_length=30)
    mobile = models.CharField(max_length=14, unique=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=16)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_customer = models.BooleanField(default=True)
    is_authenticated = True
    is_anonymous = True
    user_permissions = None
    groups = None
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'country', 'mobile', 'email', 'date_of_birth']

    def __str__(self):
        return self.username

    def get_username(self):
        return self.username

class Category(models.Model):
    category_name = models.CharField(max_length=30)
    timestamp = models.DateField(auto_now=False, auto_now_add=True)
    update = models.DateField(auto_now=True, auto_now_add=False)
    def __str__(self) -> str:
        return self.category_name
        
class CategoryVariant(models.Model):
    category = models.ForeignKey(Category, related_name='category', on_delete=models.CASCADE)
    variant_name = models.CharField(max_length=30)
    variant_unit = models.CharField(max_length=20, default='')
    def __str__(self) -> str:
        return self.variant_name

class Product(models.Model):
    product_name = models.CharField(max_length=20)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='product_category', blank=True, null=True)
    price = models.DecimalField(decimal_places=2, max_digits=100)
    has_colour_option = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)
    thumbnail = models.ImageField(default='')
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    def __str__(self) -> str:
        return self.product_name
    def get_absolute_url(self):
        return reverse('product', kwargs={'slug':self.slug})
    def save(self, *args, **kwargs):
        if self.pk != None and Product.objects.get(pk = self.pk).category != self.category:
            ProductVariant.objects.filter(product = self.pk).delete()
            super().save(*args, **kwargs, update_fields=['category'])
        else:
            super().save(*args, **kwargs)
    def delete(self):
        default_storage.delete(self.thumbnail.path)
        if self.has_colour_option:
            for c in self.product_color.all():
                default_storage.delete(c.color_image.path)
                for i in c.color_images.all():
                    default_storage.delete(i.image.path)
        else:
            for i in self.product_images.all():
                default_storage.delete(i.image.path)
        return super().delete()
    class Meta:
        unique_together = ('product_name', 'slug')
class ProductVariant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_variant')
    variant_type = models.ForeignKey(CategoryVariant, on_delete=models.CASCADE)
    unit = models.CharField(max_length=20, default='', null=True, blank=True)
    def __str__(self) -> str:
        return str(self.variant_type)
    def save(self, *args, **kwargs):
        if self.product.category == self.variant_type.category:
            super().save(*args, **kwargs)
    class Meta:
        unique_together = (('product', 'variant_type'))
class ProductVariantValue(models.Model):
    variant_type = models.ForeignKey(ProductVariant, on_delete=models.CASCADE, null=True, blank=True, related_name='variant_value')
    value = models.CharField(max_length=25)
    def __str__(self) -> str:
        return self.value
    def save(self, *args, **kwargs):
        if self.variant_type.product.category == self.variant_type.variant_type.category:
            super().save(*args, **kwargs)

class ProductColor(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_color')
    color_name= models.CharField(max_length=30)
    color_image =models.ImageField()
    # show_only_image = models.BooleanField(default=False)
    # show_only_name = models.BooleanField(default=False)
    def __str__(self) -> str:
        return self.color_name
class ProductColorImages(models.Model):
    color = models.ForeignKey(ProductColor, on_delete=models.CASCADE, related_name='color_images')
    image = models.ImageField()
    def __str__(self) -> str:
        return str(self.image)
class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_images')
    image = models.ImageField()

class Cart(models.Model):
    user = models.OneToOneField(Pearl_Users, on_delete= models.CASCADE, related_name='user_cart', null=False, blank=False, default=None)
    total = models.DecimalField(decimal_places=2, max_digits=100, default=0.00)
    timestamp = models.TimeField(auto_now = False, auto_now_add=True)
    updated = models.DateTimeField(auto_now = True, auto_now_add=False)
    def __str__(self) -> str:
        return self.user.username

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete = models.CASCADE, related_name='cart_items', blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='cart_product')
    quantity = models.IntegerField(default=1)
    notes = models.TextField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    def __str__(self) -> str:
        return f"{self.product.product_name} {self.notes}"

class CartItemVariant(models.Model):
    item = models.ForeignKey(CartItem, on_delete=models.CASCADE, related_name='cart_item_variant')
    variant = models.ForeignKey(ProductVariantValue, on_delete=models.CASCADE, related_name='cart_variant_value')
    def __str__(self) -> str:
        return f"{self.item.product.product_name} ({self.variant.value})"
class CartItemColor(models.Model):
    item = models.ForeignKey(CartItem, on_delete=models.CASCADE, related_name='cart_item_color')
    color = models.ForeignKey(ProductColor, on_delete=models.CASCADE, related_name='cart_color_value')

class Country(models.Model):
    country_name = models.CharField(max_length=20)
    country_code = models.CharField(max_length=4)
    def __str__(self) -> str:
        return self.country_name

shop/views.py
from django.contrib.auth.hashers import make_password,check_password
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout

# from .models import Product, Pearl_Users, Cart, CartItem, CategoryVariant, Product, ProductColor, ProductVariantValue
from .models import *
from math import ceil
from django.urls import reverse


def index(request):
    allprods =[]
    categorys = Category.objects.all()
    for cat in categorys:
        prod = Product.objects.filter(category=cat.id)
        n = len(prod)
        n2 = n // 2 + ceil((n / 2) - n // 2)
        n = n // 4 + ceil((n / 4) - n // 4)
        r2 = range(1, n2)
        allprods.append([prod, range(1,n), r2, n])
    params = {'allprods': allprods}
    return render(request, 'shop/index.html', params)

def about(request):
    return render(request, 'shop/about.html')

def contact(request):
    return render(request, 'shop/contact.html')

def tracker(request):
    return HttpResponse("tracker")

def productView(request,slug):
    product = Product.objects.get(slug = slug)
    product = {'product':product}
    return render(request, 'shop/productview.html', product)

def search(request):
    return HttpResponse("Search")

def checkout(request):
    return HttpResponse("check out")

def signup(request):
    if request.method == "POST":
        i =request.POST
        add = Pearl_Users(first_name=i['firstname'], last_name=i['lastname'], username=i['username'],
            password=make_password(i['password']), date_of_birth=i['date_of_birth'], country=Country.objects.get(id = i['country']).country_name,
            mobile= (Country.objects.get(id = i['country-code']).country_code+i['mobile']), email= i['email'])
        add.save()
    
    return render(request, 'shop/signup.html', {'country': Country.objects.all()})

def username_validation(request):
    try:
        uname = Pearl_Users.objects.filter(username=request.GET['e_username'])[0]
        return HttpResponse("taken")
    except:
        return HttpResponse("available")

@csrf_exempt
def login_validate(request):

    if request.method == 'POST':
        i = request.POST
        user = authenticate(username=i['username_login'], password=i['password_login'])
        if user is not None:
            login(request, user)
            return HttpResponse("valid")
        else:
            return HttpResponse("invalid")
    else:
        return HttpResponse("404-Page Not Found")

def login_page(request):
    return render(request, 'shop/login.html')

def logout_validate(request):
    try:
        logout(request)
        return HttpResponse("logout")
    except:
        return HttpResponse("error")
       
@csrf_exempt
def ajax_email_signup(request):
    if request.method == 'POST':
        i = request.POST
        try:
            user_email = Pearl_Users.objects.filter(email=i['email_signup'])[0]
            return HttpResponse("invalid")
        except:    
            return HttpResponse("valid")
            
@csrf_exempt
def ajax_mobile_signup(request):
    if request.method == "POST":
        i = request.POST
        try:
            cd = Country.objects.get(id = i['mobile_signup'].split()[0]).country_code
            user_mobile = Pearl_Users.objects.get(mobile = cd+i['mobile_signup'].split()[1])
            return HttpResponse("invalid")
        except:
            return HttpResponse("valid")

def temp(request,slug):
    product = Product.objects.get(slug = slug)
    product = {'product':product}
    return render(request, 'shop/temp.html', product)

def CartView(request):
    if request.user.is_authenticated:
        try:
            cart = Cart.objects.get(user = request.user)
        except:
            cart = Cart.objects.create(user = request.user)
        cart = {'cart':cart}
        return render(request, 'shop/cart.html', cart)
    else:
        return HttpResponseRedirect(reverse('loginpage'))

def updateCart(request, slug):
    if request.user.is_authenticated:
        try:
            qty = request.GET.get('qty')
            update_qty = True
        except:
            qty = 1
            update_qty = False
        try:
            cart = Cart.objects.get(user = request.user)
        except:
            cart = Cart.objects.create(user = request.user)
        try:
            product = Product.objects.get(slug = slug)
            try:
                itm = request.GET.get('item')
                cart_item = CartItem.objects.get(pk = itm)
            except:
                notes = '('
                if product.has_colour_option:
                    notes += (str(ProductColor.objects.get(id = str(request.GET.get('color')).split('_')[1])) + ", ")
                for variant in product.product_variant.all():
                    
                    if (variant.unit) != None and variant.unit != 'None':
                        notes += (str(ProductVariantValue.objects.get(id = request.GET.get(str(variant)))) + f"{variant.unit}, ")
                        # notes[str(variant)] = variant.unit
                    else:
                        notes += (str(ProductVariantValue.objects.get(id = request.GET.get(str(variant)))) + ", ")
                    # notes[str(variant)] = str(ProductVariantValue.objects.get(id = request.GET.get(str(variant)))) + notes[str(variant)]
                notes = notes[:-2]+')'
                cart_item, created = CartItem.objects.get_or_create(cart = cart, product = product, notes = notes)
                
                if created:
                    for variant in product.product_variant.all():
                        CartItemVariant.objects.create(item = cart_item, variant = ProductVariantValue.objects.get(id = request.GET.get(str(variant))))
                    if product.has_colour_option:
                        CartItemColor.objects.create(item = cart_item, color = ProductColor.objects.get(id = str(request.GET.get('color')).split('_')[1]))
                        

            if int(qty) == 0 and update_qty:
                cart_item.delete()
                # cart.my_cart.remove(cart_item)
            elif update_qty:
                cart_item.quantity = qty
                cart_item.notes = notes
                cart_item.save()
            else:
                pass
            
            new_total = 0
            for item in cart.cart_items.all():
                new_total += (item.product.price * item.quantity)
            cart.total = new_total
            cart.save()
            return HttpResponseRedirect(reverse('cart'))
        except:
            return HttpResponse("None")
    
    else:
        return render(request, 'shop/login.html')

def productImages(request):
    try:
        id = request.GET.get('color')
        color = ProductColor.objects.get(id=id)
        rs = f'<ul class="product-view-image-list" id="color_{id}_images">'
        ctrl = ''
        cnt = 1
        for image in color.color_images.all():
            if cnt == 1:
                ctrl += f'<button type="button" class="my-sliderbuttons active" id="ctrl_btn_{cnt}"></button>'
            else:
                ctrl += f'<button type="button" class="my-sliderbuttons" id="ctrl_btn_{cnt}"></button>'
            rs += f'<li class="small-image-li"> <img src="/media/{image.image}"></li>'
            cnt += 1
        rs += '</ul>'
        return HttpResponse(rs+'\n'+ctrl)
    except:
        return HttpResponse('')

shop/templates/shop/about.html
{% extends 'shop/basics.html' %}

shop/templates/shop/cart.html
{% extends 'shop/basics.html' %}

{% block css %}
<style>
    .checkout-btn{
        border-radius: 25px;
    }
</style>
{% endblock %}
{% block body %}

    <table class="table" style="width: 60%;" align="center">
        <thead>
            <th></th>
            <th>Product Name</th>
            <th>Price</th>
            <th>Qty</th>
            <th>Variant</th>
            <th></th>
        </thead>
        
        
        {% for item in cart.cart_items.all %}
            <tr>
                <td>
                    <div>
                        <input class="form-check-input" name="selectforcheckout" type="checkbox" id="checkboxNoLabel" value="{{item.id}}" aria-label="selectforcheckout">
                    </div>
                </td>
                <td>{{item.product.product_name}}</td>
                <td>{{item.product.price}}</td>
                <td>{{item.quantity}}</td>
                <td>{{item.notes}}</td>
                <td><a href="{% url 'cartupdate' item.product.slug %}?qty=0&item={{item.id}}">Remove</a></td>
            </tr>
        {% endfor %}
        <tr>
            <td colspan="6" align="center"><b>Total:</b> {{cart.total}}</td>
        </tr>
        <tr>
            <td colspan="6" align="center"><button type="button" class="btn btn-success checkout-btn">Checkout (Amount: {{cart.total}})</button></td>
        </tr>
    </table>

{% endblock %}

shop/templates/shop/productview.html
{% extends 'shop/basics.html' %}
{% block title %}Product View Page{% endblock %}
{% block css %}
<style type="text/css">
	.product-view {
		width: 95%;
		margin: 10px 2.5%;
		display: inline-flex;
	}

	.product-view-image {
		width: 45%;
		display: inline-flex;
	}

	.product-view-image-col {
		width: 64px;
	}

	.product-view-image-list {
		list-style: none;
		padding: 0;
		display: block;
	}

	.small-image-li {
		border: black solid 1px;
		margin: 15px 0;
		cursor: pointer;
		width: 60px;
		height: 60px;
		display: flex;
	}

	.small-image-li img {
		max-width: 100%;
		max-height: 100%;
		margin: auto;
	}

	.product-view-image-final {
		width: 100%;
		margin-left: 5%;
		display: flex;
	}

	.product-view-image-final img {
		margin: auto;
		max-width: 100%;
		max-height: 100%;
	}

	.product-view-description {
		padding-left: 2.5%;
		width: 55%;
	}

	.product-view-description-price {
		margin-top: 20px;
		line-height: 0.2rem;
		display: none;
	}

	.product-color {
		display: inline-block;
		margin-left: 4px;
		padding: 0 1.5px;

	}

	.product-color.active {
		border: black 1px solid;
	}

	.product-color img {
		width: 20px;
		height: 20px;
		border-radius: 10px;
		cursor: pointer;
		vertical-align: text-bottom;
	}

	.from-manufacturer {
		margin: 10px 2.5%;
	}


	/*New Begin from Here*/

	.product-view-image-list .small-image-li.active {
		border-color: orange;
		border-width: 2px;
	}

	.product-sizes,
	.product-rams {
		display: inline-flex;
	}

	.product-sizes div,
	.product-rams div {
		border: 1px solid black;
		padding: 0px 3px;
		border-radius: 5px;
		margin-right: 20px;
		margin-top: 5px;
		margin-bottom: 7.5px;
		cursor: pointer;
	}

	.product-sizes .active,
	.product-rams .active {
		background-color: #0dcaf0;
		border-color: #0dcaf0;
	}

	.product-view-description-price.active {
		display: block;
	}

	.product-save-price {
		display: none;
	}

	.product-save-price.active {
		display: block;
	}

	.product-mrp span {
		text-decoration: line-through !important;
	}

	.product-view-description-features,
	.product-view-description-details,
	.product-view-description-size {
		margin-top: 15px;
	}

	h5 {
		margin-bottom: 3px;
	}

	.images-control {
		display: none;
	}

	.my-sliderbuttons {
		box-sizing: content-box;
		flex: 0 1 auto;
		width: 30px;
		height: 3px;
		padding: 0;
		margin-right: 3px;
		margin-left: 3px;
		text-indent: -999px;
		cursor: pointer;
		background-color: #000;
		background-clip: padding-box;
		border: 0;
		border-top: 10px solid transparent;
		border-bottom: 10px solid transparent;
		opacity: .3;
		transition: opacity .6s ease;
	}

	.my-sliderbuttons.active {
		opacity: 1;
	}

	.product-view-description-title.big {
		display: block;
	}

	.product-view-description-title.small {
		display: none;
	}
	.product-variant-form{
		min-width: 300px;
		max-width: 500px;
		width: 70%; 
		margin-top: 30px;
		margin-bottom: 30px;
		margin-right: auto;
		margin-left: 30px;
	}
	/* Responsive Design */
	@media(max-width: 991.8px) {
		.images-control.active {
			display: inline-flex;
		}

		.product-view {
			display: block;
		}

		.product-view-image-col {
			display: none !important;
		}

		.product-view-image {
			display: block;
			width: 100%;
		}

		.product-view-image-final {
			width: 100%;
			/*height: 400px;*/
			max-width: 400px;
			padding-left: 5%;
			padding-right: 5%;
			margin-left: auto;
			margin-right: auto;
		}

		.images-control {
			width: 100%;
			justify-content: safe center;
		}

		.product-view-description-title.big {
			display: none;
		}

		.product-view-description-title.small {
			text-align: center;
			display: block;
		}

		.product-view-description {
			width: 100%;
		}
		.product-variant-form{
			margin: 30px auto;
		}
	}
	
</style>
{% endblock %}
{% block body %}

<div class="product-main-view">
	<div class="product-view">
		<div class="product-view-description-title small">
			<h3>{{product.product_name}}</h3>
		</div>
		<div class="product-view-image">
			<div class="product-view-image-col">
				{% if product.has_colour_option %}
				<ul class="product-view-image-list" id="color_{{c.id}}_images">
					{%for image in product.product_color.all.0.color_images.all %}
					<li class="small-image-li">
						<img src="/media/{{image.image}}">
					</li>
					{% endfor %}
				</ul>
				{% else %}
				<ul class="product-view-image-list">
					{%for image in product.product_images.all %}
					<li class="small-image-li">
						<img src="/media/{{image.image}}">
					</li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>

			<!-- Product Big image -->
			<div class="product-view-image-final">
				{% if product.has_colour_option %}
				<img src="/media/{{product.product_color.all.0.color_images.all.0.image}}">
				{% else %}
				<img src="/media/{{product.product_images.all.0.image}}">
				{% endif %}
			</div>

			<div class="images-control">
				{%for j in product.product_color.all.0.color_images.all %}
				{% if forloop.counter == 1 %}
				<button type="button" class="my-sliderbuttons active" id="ctrl_btn_{{forloop.counter}}"></button>
				{% else %}
				<button type="button" class="my-sliderbuttons" id="ctrl_btn_{{forloop.counter}}"></button>
				{% endif %}
				{% endfor %}
			</div>
		</div>

		<div class="product-view-description">
			<div class="product-view-description-title big">
				<h3>{{product.product_name}}</h3>
			</div>

			<!-- Price of Product -->
			<div class="product-view-description-price" id="price">
				<p class="product-price"><b>Price:</b> &#x20B9; <span>{{product.price}}</span></p>
				<!-- <p class="product-mrp"><b>M.R.P.:</b> &#x20B9; <span>{{product.0mrp}}</span></p> -->
				<!-- <p class="product-yousave"><b>You Save: </b><span></span>%</p> -->
			</div>

			<form class="product-variant-form" action="{% url 'cartupdate' product.slug %}?">
				<div class="mb-3">
					<label class="form-label">Quantity</label>
					<input type="number" name="qty" class="form-control" placeholder="1" value="1" min="0">
				</div>
				{% if product.has_colour_option %}
				<div class="mb-3">
					<label class="form-label">Color</label>
					<select class="form-select" name="color" id="id_color">
						{% for val in product.product_color.all %}
						<option value="color_{{val.id}}">{{val}}</option>
						{% endfor %}
					</select>
				</div>
				{% endif %}
				{% for variant in product.product_variant.all %}
				<div class="mb-3">
					<label class="form-label">{{variant.variant_type}}</label>
					<select class="form-select" name="{{variant.variant_type}}">
						{% for val in variant.variant_value.all %}
						<option value="{{val.id}}">{{val}}</option>
						{% endfor %}
					</select>
				</div>
				{% endfor %}

				<button type="submit" class="btn btn-primary">Add to Cart</button>
			</form>

			<div class="product-view-description-details">
				<h5>Basic Details:</h5>
				<div class="product-model"><span><b>Model:</b> {{product.product_name}}</span></div>
				<div class="product-brand"><span><b>Brand:</b> Apple</span></div>
				<div class="product-formfactor"><span><b>Form Factor:</b> Smart Phone</span></div>
			</div>
			<div class="product-view-description-features">
				<!-- <h5>Features of the Item:</h5>
				<ul class="product-features">
					<li class="product-feature">6.1-inch (15.5 cm diagonal) Super Retina XDR display</li>
					<li class="product-feature">Ceramic Shield, tougher than any smartphone glass</li>
					<li class="product-feature">A14 Bionic chip, the fastest chip ever in a smartphone</li>
					<li class="product-feature">Advanced dual-camera system with 12MP Ultra Wide and Wide cameras; Night
						mode, Deep Fusion, Smart HDR 3, 4K Dolby Vision HDR recording 12MP TrueDepth front camera with
						Night mode, 4K Dolby Vision HDR recording</li>
					<li class="product-feature">Industry-leading IP68 water resistance</li>
					<li class="product-feature">Supports MagSafe accessories for easy attach and faster wireless
						charging</li>
					<li class="product-feature">iOS with redesigned widgets on the Home screen, all-new App Library, App
						Clips and more</li>
				</ul> -->
			</div>
		</div>
	</div>
</div>
<div class="from-manufacturer">
	<div class="specifications">
		<h5>From Manufacturer:</h5>
	</div>
</div>

{% endblock %}

{% block jquery %}
<script type="text/javascript">

	// give basic active classes
	$('.product-view-image-list li').first().addClass('active');
	// $('.product-color').first().addClass('active');
	//   $('.product-sizes div').first().addClass('active');
	//   $('.product-rams div').first().addClass('active');
	//   $('.product-view-description-price').first().addClass('active');
	//   $('.product-save-price').first().addClass('active');
	//   $('.product-yousave span').text(((mrp-price)*100/mrp).toFixed(2));
	$('.images-control').first().addClass('active');
	$('.product-view-image-final').css("height", $('.product-view-image-final').width());

	// changing the color
	$(".small-image-li").click(function () {
		$(".small-image-li.active").removeClass('active');
		$(this).addClass('active');
		$('.product-view-image-final img').attr("src", $(this).find('img').attr("src"));

	});
	$(document).on("change", "select#id_color", function () {
		id = $('#id_color').children("option:selected").val().split('_')[1];
		$.ajax({
			type: 'GET',
			url: '/product_images/',
			data: {
				color: id
			},
			success: function (data) {
				$('.product-view-image-col').html(data.split('\n')[0]);
				$('.images-control.active').html(data.split('\n')[1]);
				$('.product-view-image-list li').first().addClass('active');
				$('.product-view-image-final img').attr("src", $('.product-view-image-list li img').first().attr("src"));
				$(".small-image-li").click(function () {
					$(".small-image-li.active").removeClass('active');
					$(this).addClass('active');
					$('.product-view-image-final img').attr("src", $(this).find('img').attr("src"));
				});
				$('.images-control button').click(function () {
					$('.images-control .active').removeClass('active');
					$(this).addClass('active');
					id = ($(this).attr('id')).split("_")[2];
					$('.product-view-image-list').find('.small-image-li:nth-child(' + id + ')').click();
				});
			}
		});
	});

	// changig the size of the rom
	// $('.product-sizes div').click(function(){
	// 	previous_price = rom[($('.product-sizes .active').text()).split(" ")[0]].price;
	// 	current_price = rom[($(this).text()).split(" ")[0]].price;
	// 	previous_mrp = rom[($('.product-sizes .active').text()).split(" ")[0]].mrp;
	// 	current_mrp = rom[($(this).text()).split(" ")[0]].mrp;
	// 	price = parseInt($('.product-price span').text()) - previous_price + current_price;
	// 	mrp = parseInt($('.product-mrp span').text()) - previous_mrp + current_mrp;
	// 	$('.product-sizes .active').removeClass("active");
	// 	$(this).addClass('active');
	// 	$('.product-size span').text($(this).text());
	// 	$('.product-price span').text(price);
	// 	$('.product-mrp span').text(mrp);
	// $('.product-yousave span').text(((mrp-price)*100/mrp).toFixed(2));
	// });

	$('.product-view-image-final').on('touchstart', function (e) {
		startx = e.touches[0].clientX;
		starty = e.touches[0].clientY;
	});

	$('.product-view-image-final').on('touchend', function (e) {
		endy = e.changedTouches[0].clientY;
		endx = e.changedTouches[0].clientX;
		diffx = Math.abs(endx - startx);
		diffy = Math.abs(endy - starty);
		if (diffx > diffy) {
			if (startx < endx) {
				$('.images-control.active .active').prev().click();
			}
			else if (startx > endx) {

				$('.images-control.active .active').next().click();
			}
		}
	});

	$('.images-control button').click(function () {
		$('.images-control .active').removeClass('active');
		$(this).addClass('active');
		id = ($(this).attr('id')).split("_")[2];
		$('.product-view-image-list').find('.small-image-li:nth-child(' + id + ')').click();
	});

</script>
{% endblock %}

shop/templates/shop/tracker.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>